// Code generated by controller-gen. DO NOT EDIT.

package v1

// AggregateGroupApplyConfiguration represents a declarative configuration of the AggregateGroup type for use
// with apply.
type AggregateGroupApplyConfiguration struct {
	Name     *string           `json:"name,omitempty"`
	UUID     *string           `json:"uuid,omitempty"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// AggregateGroupApplyConfiguration constructs a declarative configuration of the AggregateGroup type for use with
// apply.
func AggregateGroup() *AggregateGroupApplyConfiguration {
	return &AggregateGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AggregateGroupApplyConfiguration) WithName(value string) *AggregateGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithUUID sets the UUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UUID field is set to the value of the last call.
func (b *AggregateGroupApplyConfiguration) WithUUID(value string) *AggregateGroupApplyConfiguration {
	b.UUID = &value
	return b
}

// WithMetadata puts the entries into the Metadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Metadata field,
// overwriting an existing map entries in Metadata field with the same key.
func (b *AggregateGroupApplyConfiguration) WithMetadata(entries map[string]string) *AggregateGroupApplyConfiguration {
	if b.Metadata == nil && len(entries) > 0 {
		b.Metadata = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Metadata[k] = v
	}
	return b
}
