// Code generated by controller-gen. DO NOT EDIT.

package v1

// AggregateApplyConfiguration represents a declarative configuration of the Aggregate type for use
// with apply.
type AggregateApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	UUID *string `json:"uuid,omitempty"`
}

// AggregateApplyConfiguration constructs a declarative configuration of the Aggregate type for use with
// apply.
func Aggregate() *AggregateApplyConfiguration {
	return &AggregateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AggregateApplyConfiguration) WithName(value string) *AggregateApplyConfiguration {
	b.Name = &value
	return b
}

// WithUUID sets the UUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UUID field is set to the value of the last call.
func (b *AggregateApplyConfiguration) WithUUID(value string) *AggregateApplyConfiguration {
	b.UUID = &value
	return b
}
