// Code generated by controller-gen. DO NOT EDIT.

package v1

// BookingApplyConfiguration represents a declarative configuration of the Booking type for use
// with apply.
type BookingApplyConfiguration struct {
	Consumer    *ConsumerBookingApplyConfiguration    `json:"consumer,omitempty"`
	Reservation *ReservationBookingApplyConfiguration `json:"reservation,omitempty"`
}

// BookingApplyConfiguration constructs a declarative configuration of the Booking type for use with
// apply.
func Booking() *BookingApplyConfiguration {
	return &BookingApplyConfiguration{}
}

// WithConsumer sets the Consumer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Consumer field is set to the value of the last call.
func (b *BookingApplyConfiguration) WithConsumer(value *ConsumerBookingApplyConfiguration) *BookingApplyConfiguration {
	b.Consumer = value
	return b
}

// WithReservation sets the Reservation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reservation field is set to the value of the last call.
func (b *BookingApplyConfiguration) WithReservation(value *ReservationBookingApplyConfiguration) *BookingApplyConfiguration {
	b.Reservation = value
	return b
}
