// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CapabilitiesApplyConfiguration represents a declarative configuration of the Capabilities type for use
// with apply.
//
// Capabilities of the hypervisor as reported by libvirt.
type CapabilitiesApplyConfiguration struct {
	// The hosts CPU architecture (not the guests).
	HostCpuArch *string `json:"cpuArch,omitempty"`
	// Total host memory available as a sum of memory over all numa cells.
	HostMemory *resource.Quantity `json:"memory,omitempty"`
	// Total host cpus available as a sum of cpus over all numa cells.
	HostCpus *resource.Quantity `json:"cpus,omitempty"`
}

// CapabilitiesApplyConfiguration constructs a declarative configuration of the Capabilities type for use with
// apply.
func Capabilities() *CapabilitiesApplyConfiguration {
	return &CapabilitiesApplyConfiguration{}
}

// WithHostCpuArch sets the HostCpuArch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostCpuArch field is set to the value of the last call.
func (b *CapabilitiesApplyConfiguration) WithHostCpuArch(value string) *CapabilitiesApplyConfiguration {
	b.HostCpuArch = &value
	return b
}

// WithHostMemory sets the HostMemory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostMemory field is set to the value of the last call.
func (b *CapabilitiesApplyConfiguration) WithHostMemory(value resource.Quantity) *CapabilitiesApplyConfiguration {
	b.HostMemory = &value
	return b
}

// WithHostCpus sets the HostCpus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostCpus field is set to the value of the last call.
func (b *CapabilitiesApplyConfiguration) WithHostCpus(value resource.Quantity) *CapabilitiesApplyConfiguration {
	b.HostCpus = &value
	return b
}
