// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CellApplyConfiguration represents a declarative configuration of the Cell type for use
// with apply.
type CellApplyConfiguration struct {
	ID       *int                         `json:"id,omitempty"`
	Capacity map[string]resource.Quantity `json:"capacity,omitempty"`
}

// CellApplyConfiguration constructs a declarative configuration of the Cell type for use with
// apply.
func Cell() *CellApplyConfiguration {
	return &CellApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *CellApplyConfiguration) WithID(value int) *CellApplyConfiguration {
	b.ID = &value
	return b
}

// WithCapacity puts the entries into the Capacity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Capacity field,
// overwriting an existing map entries in Capacity field with the same key.
func (b *CellApplyConfiguration) WithCapacity(entries map[string]resource.Quantity) *CellApplyConfiguration {
	if b.Capacity == nil && len(entries) > 0 {
		b.Capacity = make(map[string]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Capacity[k] = v
	}
	return b
}
