// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// CellApplyConfiguration represents a declarative configuration of the Cell type for use
// with apply.
type CellApplyConfiguration struct {
	CellID     *uint64                      `json:"cellID,omitempty"`
	Allocation map[string]resource.Quantity `json:"allocation,omitempty"`
	Capacity   map[string]resource.Quantity `json:"capacity,omitempty"`
}

// CellApplyConfiguration constructs a declarative configuration of the Cell type for use with
// apply.
func Cell() *CellApplyConfiguration {
	return &CellApplyConfiguration{}
}

// WithCellID sets the CellID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CellID field is set to the value of the last call.
func (b *CellApplyConfiguration) WithCellID(value uint64) *CellApplyConfiguration {
	b.CellID = &value
	return b
}

// WithAllocation puts the entries into the Allocation field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Allocation field,
// overwriting an existing map entries in Allocation field with the same key.
func (b *CellApplyConfiguration) WithAllocation(entries map[string]resource.Quantity) *CellApplyConfiguration {
	if b.Allocation == nil && len(entries) > 0 {
		b.Allocation = make(map[string]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Allocation[k] = v
	}
	return b
}

// WithCapacity puts the entries into the Capacity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Capacity field,
// overwriting an existing map entries in Capacity field with the same key.
func (b *CellApplyConfiguration) WithCapacity(entries map[string]resource.Quantity) *CellApplyConfiguration {
	if b.Capacity == nil && len(entries) > 0 {
		b.Capacity = make(map[string]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Capacity[k] = v
	}
	return b
}
