// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ConsumerBookingApplyConfiguration represents a declarative configuration of the ConsumerBooking type for use
// with apply.
type ConsumerBookingApplyConfiguration struct {
	UUID               *string                                  `json:"uuid,omitempty"`
	Resources          map[apiv1.ResourceName]resource.Quantity `json:"resources,omitempty"`
	ConsumerGeneration *int64                                   `json:"consumerGeneration,omitempty"`
	ConsumerType       *string                                  `json:"consumerType,omitempty"`
	ProjectID          *string                                  `json:"projectID,omitempty"`
	UserID             *string                                  `json:"userID,omitempty"`
}

// ConsumerBookingApplyConfiguration constructs a declarative configuration of the ConsumerBooking type for use with
// apply.
func ConsumerBooking() *ConsumerBookingApplyConfiguration {
	return &ConsumerBookingApplyConfiguration{}
}

// WithUUID sets the UUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UUID field is set to the value of the last call.
func (b *ConsumerBookingApplyConfiguration) WithUUID(value string) *ConsumerBookingApplyConfiguration {
	b.UUID = &value
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *ConsumerBookingApplyConfiguration) WithResources(entries map[apiv1.ResourceName]resource.Quantity) *ConsumerBookingApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[apiv1.ResourceName]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}

// WithConsumerGeneration sets the ConsumerGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumerGeneration field is set to the value of the last call.
func (b *ConsumerBookingApplyConfiguration) WithConsumerGeneration(value int64) *ConsumerBookingApplyConfiguration {
	b.ConsumerGeneration = &value
	return b
}

// WithConsumerType sets the ConsumerType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumerType field is set to the value of the last call.
func (b *ConsumerBookingApplyConfiguration) WithConsumerType(value string) *ConsumerBookingApplyConfiguration {
	b.ConsumerType = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *ConsumerBookingApplyConfiguration) WithProjectID(value string) *ConsumerBookingApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithUserID sets the UserID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserID field is set to the value of the last call.
func (b *ConsumerBookingApplyConfiguration) WithUserID(value string) *ConsumerBookingApplyConfiguration {
	b.UserID = &value
	return b
}
