// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// DomainInfoApplyConfiguration represents a declarative configuration of the DomainInfo type for use
// with apply.
type DomainInfoApplyConfiguration struct {
	Name        *string                      `json:"name,omitempty"`
	UUID        *string                      `json:"uuid,omitempty"`
	Allocation  map[string]resource.Quantity `json:"allocation,omitempty"`
	MemoryCells []int                        `json:"memoryCells,omitempty"`
	CpuCells    []int                        `json:"cpuCells,omitempty"`
}

// DomainInfoApplyConfiguration constructs a declarative configuration of the DomainInfo type for use with
// apply.
func DomainInfo() *DomainInfoApplyConfiguration {
	return &DomainInfoApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DomainInfoApplyConfiguration) WithName(value string) *DomainInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithUUID sets the UUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UUID field is set to the value of the last call.
func (b *DomainInfoApplyConfiguration) WithUUID(value string) *DomainInfoApplyConfiguration {
	b.UUID = &value
	return b
}

// WithAllocation puts the entries into the Allocation field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Allocation field,
// overwriting an existing map entries in Allocation field with the same key.
func (b *DomainInfoApplyConfiguration) WithAllocation(entries map[string]resource.Quantity) *DomainInfoApplyConfiguration {
	if b.Allocation == nil && len(entries) > 0 {
		b.Allocation = make(map[string]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Allocation[k] = v
	}
	return b
}

// WithMemoryCells adds the given value to the MemoryCells field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MemoryCells field.
func (b *DomainInfoApplyConfiguration) WithMemoryCells(values ...int) *DomainInfoApplyConfiguration {
	for i := range values {
		b.MemoryCells = append(b.MemoryCells, values[i])
	}
	return b
}

// WithCpuCells adds the given value to the CpuCells field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CpuCells field.
func (b *DomainInfoApplyConfiguration) WithCpuCells(values ...int) *DomainInfoApplyConfiguration {
	for i := range values {
		b.CpuCells = append(b.CpuCells, values[i])
	}
	return b
}
