// Code generated by controller-gen. DO NOT EDIT.

package v1

// DomainCapabilitiesApplyConfiguration represents a declarative configuration of the DomainCapabilities type for use
// with apply.
//
// Domain capabilities of the hypervisor as reported by libvirt.
// These details are relevant to check if a VM can be scheduled on the hypervisor.
type DomainCapabilitiesApplyConfiguration struct {
	// The available domain cpu architecture.
	Arch *string `json:"arch,omitempty"`
	// The supported type of virtualization for domains, such as "ch".
	HypervisorType *string `json:"hypervisorType,omitempty"`
	// Supported devices for domains.
	//
	// The format of this list is the device type, and if specified, a specific
	// model. For example, take the following xml domain device definition:
	//
	// <video supported='yes'>
	// <enum name='modelType'>
	// <value>nvidia</value>
	// </enum>
	// </video>
	//
	// The corresponding entries in this list would be "video" and "video/nvidia".
	SupportedDevices []string `json:"supportedDevices,omitempty"`
	// Supported cpu modes for domains.
	//
	// The format of this list is cpu mode, and if specified, a specific
	// submode. For example, take the following xml domain cpu definition:
	//
	// <mode name='host-passthrough' supported='yes'>
	// <enum name='hostPassthroughMigratable'/>
	// </mode>
	//
	// The corresponding entries in this list would be "host-passthrough" and
	// "host-passthrough/migratable".
	SupportedCpuModes []string `json:"supportedCpuModes,omitempty"`
	// Supported features for domains, such as "sev" or "sgx".
	//
	// This is a flat list of supported features, meaning the following xml:
	//
	// <features>
	// <sev supported='no'/>
	// <sgx supported='no'/>
	// </features>
	//
	// Would correspond to the entries "sev" and "sgx" in this list.
	SupportedFeatures []string `json:"supportedFeatures,omitempty"`
}

// DomainCapabilitiesApplyConfiguration constructs a declarative configuration of the DomainCapabilities type for use with
// apply.
func DomainCapabilities() *DomainCapabilitiesApplyConfiguration {
	return &DomainCapabilitiesApplyConfiguration{}
}

// WithArch sets the Arch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Arch field is set to the value of the last call.
func (b *DomainCapabilitiesApplyConfiguration) WithArch(value string) *DomainCapabilitiesApplyConfiguration {
	b.Arch = &value
	return b
}

// WithHypervisorType sets the HypervisorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HypervisorType field is set to the value of the last call.
func (b *DomainCapabilitiesApplyConfiguration) WithHypervisorType(value string) *DomainCapabilitiesApplyConfiguration {
	b.HypervisorType = &value
	return b
}

// WithSupportedDevices adds the given value to the SupportedDevices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedDevices field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedDevices(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedDevices = append(b.SupportedDevices, values[i])
	}
	return b
}

// WithSupportedCpuModes adds the given value to the SupportedCpuModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedCpuModes field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedCpuModes(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedCpuModes = append(b.SupportedCpuModes, values[i])
	}
	return b
}

// WithSupportedFeatures adds the given value to the SupportedFeatures field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedFeatures field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedFeatures(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedFeatures = append(b.SupportedFeatures, values[i])
	}
	return b
}
