// Code generated by controller-gen. DO NOT EDIT.

package v1

// DomainCapabilitiesApplyConfiguration represents a declarative configuration of the DomainCapabilities type for use
// with apply.
type DomainCapabilitiesApplyConfiguration struct {
	Arch              *string  `json:"arch,omitempty"`
	HypervisorType    *string  `json:"hypervisorType,omitempty"`
	SupportedDevices  []string `json:"supportedDevices,omitempty"`
	SupportedCpuModes []string `json:"supportedCpuModes,omitempty"`
	SupportedFeatures []string `json:"supportedFeatures,omitempty"`
}

// DomainCapabilitiesApplyConfiguration constructs a declarative configuration of the DomainCapabilities type for use with
// apply.
func DomainCapabilities() *DomainCapabilitiesApplyConfiguration {
	return &DomainCapabilitiesApplyConfiguration{}
}

// WithArch sets the Arch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Arch field is set to the value of the last call.
func (b *DomainCapabilitiesApplyConfiguration) WithArch(value string) *DomainCapabilitiesApplyConfiguration {
	b.Arch = &value
	return b
}

// WithHypervisorType sets the HypervisorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HypervisorType field is set to the value of the last call.
func (b *DomainCapabilitiesApplyConfiguration) WithHypervisorType(value string) *DomainCapabilitiesApplyConfiguration {
	b.HypervisorType = &value
	return b
}

// WithSupportedDevices adds the given value to the SupportedDevices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedDevices field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedDevices(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedDevices = append(b.SupportedDevices, values[i])
	}
	return b
}

// WithSupportedCpuModes adds the given value to the SupportedCpuModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedCpuModes field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedCpuModes(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedCpuModes = append(b.SupportedCpuModes, values[i])
	}
	return b
}

// WithSupportedFeatures adds the given value to the SupportedFeatures field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedFeatures field.
func (b *DomainCapabilitiesApplyConfiguration) WithSupportedFeatures(values ...string) *DomainCapabilitiesApplyConfiguration {
	for i := range values {
		b.SupportedFeatures = append(b.SupportedFeatures, values[i])
	}
	return b
}
