// Code generated by controller-gen. DO NOT EDIT.

package v1

// EvictionSpecApplyConfiguration represents a declarative configuration of the EvictionSpec type for use
// with apply.
type EvictionSpecApplyConfiguration struct {
	Hypervisor *string `json:"hypervisor,omitempty"`
	Reason     *string `json:"reason,omitempty"`
}

// EvictionSpecApplyConfiguration constructs a declarative configuration of the EvictionSpec type for use with
// apply.
func EvictionSpec() *EvictionSpecApplyConfiguration {
	return &EvictionSpecApplyConfiguration{}
}

// WithHypervisor sets the Hypervisor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hypervisor field is set to the value of the last call.
func (b *EvictionSpecApplyConfiguration) WithHypervisor(value string) *EvictionSpecApplyConfiguration {
	b.Hypervisor = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *EvictionSpecApplyConfiguration) WithReason(value string) *EvictionSpecApplyConfiguration {
	b.Reason = &value
	return b
}
