/*
SPDX-FileCopyrightText: Copyright 2024 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1

// EvictionSpecApplyConfiguration represents a declarative configuration of the EvictionSpec type for use
// with apply.
type EvictionSpecApplyConfiguration struct {
	Hypervisor *string `json:"hypervisor,omitempty"`
	Reason     *string `json:"reason,omitempty"`
}

// EvictionSpecApplyConfiguration constructs a declarative configuration of the EvictionSpec type for use with
// apply.
func EvictionSpec() *EvictionSpecApplyConfiguration {
	return &EvictionSpecApplyConfiguration{}
}

// WithHypervisor sets the Hypervisor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hypervisor field is set to the value of the last call.
func (b *EvictionSpecApplyConfiguration) WithHypervisor(value string) *EvictionSpecApplyConfiguration {
	b.Hypervisor = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *EvictionSpecApplyConfiguration) WithReason(value string) *EvictionSpecApplyConfiguration {
	b.Reason = &value
	return b
}
