// Code generated by controller-gen. DO NOT EDIT.

package v1

// GroupApplyConfiguration represents a declarative configuration of the Group type for use
// with apply.
//
// Group is a typed group membership entry for a hypervisor.
//
// This follows the field-presence union pattern (as used by
// PodSpec.volumes in core Kubernetes): each entry populates exactly
// one type-specific sub-field, and the populated field identifies
// the group type.
type GroupApplyConfiguration struct {
	Trait     *TraitGroupApplyConfiguration     `json:"trait,omitempty"`
	Aggregate *AggregateGroupApplyConfiguration `json:"aggregate,omitempty"`
}

// GroupApplyConfiguration constructs a declarative configuration of the Group type for use with
// apply.
func Group() *GroupApplyConfiguration {
	return &GroupApplyConfiguration{}
}

// WithTrait sets the Trait field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trait field is set to the value of the last call.
func (b *GroupApplyConfiguration) WithTrait(value *TraitGroupApplyConfiguration) *GroupApplyConfiguration {
	b.Trait = value
	return b
}

// WithAggregate sets the Aggregate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggregate field is set to the value of the last call.
func (b *GroupApplyConfiguration) WithAggregate(value *AggregateGroupApplyConfiguration) *GroupApplyConfiguration {
	b.Aggregate = value
	return b
}
