// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HypervisorConfigSetSpecApplyConfiguration represents a declarative configuration of the HypervisorConfigSetSpec type for use
// with apply.
type HypervisorConfigSetSpecApplyConfiguration struct {
	Selector *metav1.LabelSelectorApplyConfiguration        `json:"selector,omitempty"`
	Template *HypervisorConfigSetTemplateApplyConfiguration `json:"template,omitempty"`
}

// HypervisorConfigSetSpecApplyConfiguration constructs a declarative configuration of the HypervisorConfigSetSpec type for use with
// apply.
func HypervisorConfigSetSpec() *HypervisorConfigSetSpecApplyConfiguration {
	return &HypervisorConfigSetSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *HypervisorConfigSetSpecApplyConfiguration) WithSelector(value *metav1.LabelSelectorApplyConfiguration) *HypervisorConfigSetSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *HypervisorConfigSetSpecApplyConfiguration) WithTemplate(value *HypervisorConfigSetTemplateApplyConfiguration) *HypervisorConfigSetSpecApplyConfiguration {
	b.Template = value
	return b
}
