// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	internal "github.com/cobaltcore-dev/openstack-hypervisor-operator/applyconfigurations/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HypervisorConfigOverrideApplyConfiguration represents a declarative configuration of the HypervisorConfigOverride type for use
// with apply.
//
// HypervisorConfigOverride is the Schema for overriding the config of one hypervisor crd API
type HypervisorConfigOverrideApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *HypervisorConfigOverrideSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *HypervisorConfigOverrideStatusApplyConfiguration `json:"status,omitempty"`
}

// HypervisorConfigOverride constructs a declarative configuration of the HypervisorConfigOverride type for use with
// apply.
func HypervisorConfigOverride(name string) *HypervisorConfigOverrideApplyConfiguration {
	b := &HypervisorConfigOverrideApplyConfiguration{}
	b.WithName(name)
	b.WithKind("HypervisorConfigOverride")
	b.WithAPIVersion("kvm.cloud.sap/v1")
	return b
}

// ExtractHypervisorConfigOverrideFrom extracts the applied configuration owned by fieldManager from
// hypervisorConfigOverride for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// hypervisorConfigOverride must be a unmodified HypervisorConfigOverride API object that was retrieved from the Kubernetes API.
// ExtractHypervisorConfigOverrideFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractHypervisorConfigOverrideFrom(hypervisorConfigOverride *apiv1.HypervisorConfigOverride, fieldManager string, subresource string) (*HypervisorConfigOverrideApplyConfiguration, error) {
	b := &HypervisorConfigOverrideApplyConfiguration{}
	err := managedfields.ExtractInto(hypervisorConfigOverride, internal.Parser().Type("com.github.cobaltcore-dev.openstack-hypervisor-operator.api.v1.HypervisorConfigOverride"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(hypervisorConfigOverride.Name)

	b.WithKind("HypervisorConfigOverride")
	b.WithAPIVersion("kvm.cloud.sap/v1")
	return b, nil
}

// ExtractHypervisorConfigOverride extracts the applied configuration owned by fieldManager from
// hypervisorConfigOverride. If no managedFields are found in hypervisorConfigOverride for fieldManager, a
// HypervisorConfigOverrideApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// hypervisorConfigOverride must be a unmodified HypervisorConfigOverride API object that was retrieved from the Kubernetes API.
// ExtractHypervisorConfigOverride provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractHypervisorConfigOverride(hypervisorConfigOverride *apiv1.HypervisorConfigOverride, fieldManager string) (*HypervisorConfigOverrideApplyConfiguration, error) {
	return ExtractHypervisorConfigOverrideFrom(hypervisorConfigOverride, fieldManager, "")
}

// ExtractHypervisorConfigOverrideStatus extracts the applied configuration owned by fieldManager from
// hypervisorConfigOverride for the status subresource.
func ExtractHypervisorConfigOverrideStatus(hypervisorConfigOverride *apiv1.HypervisorConfigOverride, fieldManager string) (*HypervisorConfigOverrideApplyConfiguration, error) {
	return ExtractHypervisorConfigOverrideFrom(hypervisorConfigOverride, fieldManager, "status")
}

func (b HypervisorConfigOverrideApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithKind(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithAPIVersion(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithName(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithGenerateName(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithNamespace(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithUID(value types.UID) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithResourceVersion(value string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithGeneration(value int64) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *HypervisorConfigOverrideApplyConfiguration) WithLabels(entries map[string]string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *HypervisorConfigOverrideApplyConfiguration) WithAnnotations(entries map[string]string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *HypervisorConfigOverrideApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *HypervisorConfigOverrideApplyConfiguration) WithFinalizers(values ...string) *HypervisorConfigOverrideApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *HypervisorConfigOverrideApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithSpec(value *HypervisorConfigOverrideSpecApplyConfiguration) *HypervisorConfigOverrideApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *HypervisorConfigOverrideApplyConfiguration) WithStatus(value *HypervisorConfigOverrideStatusApplyConfiguration) *HypervisorConfigOverrideApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *HypervisorConfigOverrideApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *HypervisorConfigOverrideApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *HypervisorConfigOverrideApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *HypervisorConfigOverrideApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
