// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
)

// HypervisorSpecApplyConfiguration represents a declarative configuration of the HypervisorSpec type for use
// with apply.
//
// HypervisorSpec defines the desired state of Hypervisor
type HypervisorSpecApplyConfiguration struct {
	// OperatingSystemVersion represents the desired operating system version.
	OperatingSystemVersion *string `json:"version,omitempty"`
	// Reboot requests a reboot after successful installation of an upgrade.
	Reboot *bool `json:"reboot,omitempty"`
	// EvacuateOnReboot requests an evacuation of all instances before reboot.
	EvacuateOnReboot *bool `json:"evacuateOnReboot,omitempty"`
	// LifecycleEnabled enables the lifecycle management of the hypervisor via hypervisor-operator.
	LifecycleEnabled *bool `json:"lifecycleEnabled,omitempty"`
	// SkipTests skips the tests during the onboarding process.
	SkipTests *bool `json:"skipTests,omitempty"`
	// CustomTraits are used to apply custom traits to the hypervisor.
	CustomTraits []string `json:"customTraits,omitempty"`
	// Aggregates are used to apply aggregates to the hypervisor.
	Aggregates []string `json:"aggregates,omitempty"`
	// Groups defines typed group memberships for this hypervisor.
	//
	// Both traits and aggregates are forms of grouping: traits group
	// hypervisors by capability, aggregates group them by administrative
	// assignment. Each entry follows the field-presence union pattern
	// (as used by PodSpec.volumes in core Kubernetes): exactly one
	// type-specific sub-field must be populated per entry.
	//
	// The Cortex Placement shim and scheduler read group memberships
	// directly from this field.
	//
	// Note: uniqueness of trait names and aggregate UUIDs is not enforced
	// via CEL because the required O(n^2) comparison exceeds the
	// Kubernetes CEL cost budget. Enforce uniqueness in the consuming
	// controller or via a validating webhook if needed.
	Groups []GroupApplyConfiguration `json:"groups,omitempty"`
	// AllowedProjects defines which openstack projects are allowed to schedule
	// instances on this hypervisor. The values of this list should be project
	// uuids. If left empty, all projects are allowed.
	AllowedProjects []string `json:"allowedProjects,omitempty"`
	// HighAvailability is used to enable the high availability handling of the hypervisor.
	HighAvailability *bool `json:"highAvailability,omitempty"`
	// CreateCertManagerCertificate requests that a certificate be issued from
	// cert-manager for the hypervisor, to be used for secure communication
	// with the libvirt API.
	CreateCertManagerCertificate *bool `json:"createCertManagerCertificate,omitempty"`
	// InstallCertificate enables installation of certificates via kvm-node-agent.
	InstallCertificate *bool `json:"installCertificate,omitempty"`
	// Maintenance indicates whether the hypervisor is in maintenance mode.
	Maintenance *string `json:"maintenance,omitempty"`
	// MaintenanceReason provides the reason for manual maintenance mode.
	MaintenanceReason *string `json:"maintenanceReason,omitempty"`
	// Overcommit specifies the desired overcommit ratio by resource type.
	//
	// If no overcommit is specified for a resource type, the default overcommit
	// ratio of 1.0 should be applied, i.e. the effective capacity is the same
	// as the actual capacity.
	//
	// If the overcommit ratio results in a fractional effective capacity,
	// the effective capacity is expected to be rounded down. This allows
	// gradually adjusting the hypervisor capacity.
	//
	// It is validated that all overcommit ratios are greater than or equal to
	// 1.0, if specified. For this we don't need extra validating webhooks.
	// See: https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/#crd-transition-rules
	Overcommit map[apiv1.ResourceName]float64 `json:"overcommit,omitempty"`
}

// HypervisorSpecApplyConfiguration constructs a declarative configuration of the HypervisorSpec type for use with
// apply.
func HypervisorSpec() *HypervisorSpecApplyConfiguration {
	return &HypervisorSpecApplyConfiguration{}
}

// WithOperatingSystemVersion sets the OperatingSystemVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingSystemVersion field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithOperatingSystemVersion(value string) *HypervisorSpecApplyConfiguration {
	b.OperatingSystemVersion = &value
	return b
}

// WithReboot sets the Reboot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reboot field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithReboot(value bool) *HypervisorSpecApplyConfiguration {
	b.Reboot = &value
	return b
}

// WithEvacuateOnReboot sets the EvacuateOnReboot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvacuateOnReboot field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithEvacuateOnReboot(value bool) *HypervisorSpecApplyConfiguration {
	b.EvacuateOnReboot = &value
	return b
}

// WithLifecycleEnabled sets the LifecycleEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleEnabled field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithLifecycleEnabled(value bool) *HypervisorSpecApplyConfiguration {
	b.LifecycleEnabled = &value
	return b
}

// WithSkipTests sets the SkipTests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipTests field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithSkipTests(value bool) *HypervisorSpecApplyConfiguration {
	b.SkipTests = &value
	return b
}

// WithCustomTraits adds the given value to the CustomTraits field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomTraits field.
func (b *HypervisorSpecApplyConfiguration) WithCustomTraits(values ...string) *HypervisorSpecApplyConfiguration {
	for i := range values {
		b.CustomTraits = append(b.CustomTraits, values[i])
	}
	return b
}

// WithAggregates adds the given value to the Aggregates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Aggregates field.
func (b *HypervisorSpecApplyConfiguration) WithAggregates(values ...string) *HypervisorSpecApplyConfiguration {
	for i := range values {
		b.Aggregates = append(b.Aggregates, values[i])
	}
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *HypervisorSpecApplyConfiguration) WithGroups(values ...*GroupApplyConfiguration) *HypervisorSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithGroups")
		}
		b.Groups = append(b.Groups, *values[i])
	}
	return b
}

// WithAllowedProjects adds the given value to the AllowedProjects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedProjects field.
func (b *HypervisorSpecApplyConfiguration) WithAllowedProjects(values ...string) *HypervisorSpecApplyConfiguration {
	for i := range values {
		b.AllowedProjects = append(b.AllowedProjects, values[i])
	}
	return b
}

// WithHighAvailability sets the HighAvailability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighAvailability field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithHighAvailability(value bool) *HypervisorSpecApplyConfiguration {
	b.HighAvailability = &value
	return b
}

// WithCreateCertManagerCertificate sets the CreateCertManagerCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateCertManagerCertificate field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithCreateCertManagerCertificate(value bool) *HypervisorSpecApplyConfiguration {
	b.CreateCertManagerCertificate = &value
	return b
}

// WithInstallCertificate sets the InstallCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallCertificate field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithInstallCertificate(value bool) *HypervisorSpecApplyConfiguration {
	b.InstallCertificate = &value
	return b
}

// WithMaintenance sets the Maintenance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maintenance field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithMaintenance(value string) *HypervisorSpecApplyConfiguration {
	b.Maintenance = &value
	return b
}

// WithMaintenanceReason sets the MaintenanceReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaintenanceReason field is set to the value of the last call.
func (b *HypervisorSpecApplyConfiguration) WithMaintenanceReason(value string) *HypervisorSpecApplyConfiguration {
	b.MaintenanceReason = &value
	return b
}

// WithOvercommit puts the entries into the Overcommit field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Overcommit field,
// overwriting an existing map entries in Overcommit field with the same key.
func (b *HypervisorSpecApplyConfiguration) WithOvercommit(entries map[apiv1.ResourceName]float64) *HypervisorSpecApplyConfiguration {
	if b.Overcommit == nil && len(entries) > 0 {
		b.Overcommit = make(map[apiv1.ResourceName]float64, len(entries))
	}
	for k, v := range entries {
		b.Overcommit[k] = v
	}
	return b
}
