// Code generated by controller-gen. DO NOT EDIT.

package v1

// HypervisorConfigSpecApplyConfiguration represents a declarative configuration of the HypervisorConfigSpec type for use
// with apply.
//
// HypervisorConfigSpec defines (in parts) the desired state of Hypervisor
type HypervisorConfigSpecApplyConfiguration struct {
	// OperatingSystemVersion represents the desired operating system version.
	OperatingSystemVersion *string `json:"version,omitempty"`
	// Reboot request an reboot after successful installation of an upgrade.
	Reboot *bool `json:"reboot,omitempty"`
	// EvacuateOnReboot request an evacuation of all instances before reboot.
	EvacuateOnReboot *bool `json:"evacuateOnReboot,omitempty"`
	// LifecycleEnabled enables the lifecycle management of the hypervisor via hypervisor-operator.
	LifecycleEnabled *bool `json:"lifecycleEnabled,omitempty"`
	// SkipTests skips the tests during the onboarding process.
	SkipTests *bool `json:"skipTests,omitempty"`
	// CustomTraits are used to apply custom traits to the hypervisor.
	CustomTraits *[]string `json:"customTraits,omitempty"`
	// Aggregates are used to apply aggregates to the hypervisor.
	Aggregates *[]string `json:"aggregates,omitempty"`
	// HighAvailability is used to enable the high availability handling of the hypervisor.
	HighAvailability *bool `json:"highAvailability,omitempty"`
	// Require to issue a certificate from cert-manager for the hypervisor, to be used for
	// secure communication with the libvirt API.
	CreateCertManagerCertificate *bool `json:"createCertManagerCertificate,omitempty"`
	// InstallCertificate is used to enable the installations of the certificates via kvm-node-agent.
	InstallCertificate *bool `json:"installCertificate,omitempty"`
	// Maintenance indicates whether the hypervisor is in maintenance mode.
	Maintenance *string `json:"maintenance,omitempty"`
}

// HypervisorConfigSpecApplyConfiguration constructs a declarative configuration of the HypervisorConfigSpec type for use with
// apply.
func HypervisorConfigSpec() *HypervisorConfigSpecApplyConfiguration {
	return &HypervisorConfigSpecApplyConfiguration{}
}

// WithOperatingSystemVersion sets the OperatingSystemVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingSystemVersion field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithOperatingSystemVersion(value string) *HypervisorConfigSpecApplyConfiguration {
	b.OperatingSystemVersion = &value
	return b
}

// WithReboot sets the Reboot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reboot field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithReboot(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.Reboot = &value
	return b
}

// WithEvacuateOnReboot sets the EvacuateOnReboot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EvacuateOnReboot field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithEvacuateOnReboot(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.EvacuateOnReboot = &value
	return b
}

// WithLifecycleEnabled sets the LifecycleEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleEnabled field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithLifecycleEnabled(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.LifecycleEnabled = &value
	return b
}

// WithSkipTests sets the SkipTests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipTests field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithSkipTests(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.SkipTests = &value
	return b
}

// WithCustomTraits sets the CustomTraits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomTraits field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithCustomTraits(value []string) *HypervisorConfigSpecApplyConfiguration {
	b.CustomTraits = &value
	return b
}

// WithAggregates sets the Aggregates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Aggregates field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithAggregates(value []string) *HypervisorConfigSpecApplyConfiguration {
	b.Aggregates = &value
	return b
}

// WithHighAvailability sets the HighAvailability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighAvailability field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithHighAvailability(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.HighAvailability = &value
	return b
}

// WithCreateCertManagerCertificate sets the CreateCertManagerCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateCertManagerCertificate field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithCreateCertManagerCertificate(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.CreateCertManagerCertificate = &value
	return b
}

// WithInstallCertificate sets the InstallCertificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallCertificate field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithInstallCertificate(value bool) *HypervisorConfigSpecApplyConfiguration {
	b.InstallCertificate = &value
	return b
}

// WithMaintenance sets the Maintenance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maintenance field is set to the value of the last call.
func (b *HypervisorConfigSpecApplyConfiguration) WithMaintenance(value string) *HypervisorConfigSpecApplyConfiguration {
	b.Maintenance = &value
	return b
}
