// Code generated by controller-gen. DO NOT EDIT.

package v1

// HypervisorConfigOverrideSpecApplyConfiguration represents a declarative configuration of the HypervisorConfigOverrideSpec type for use
// with apply.
//
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
// Important: Run "make" to regenerate code after modifying this file
// HypervisorConfigOverrideSpec overrides the desired state of Hypervisor
type HypervisorConfigOverrideSpecApplyConfiguration struct {
	// Reason describes the reason for the override
	Reason   *string                                 `json:"reason,omitempty"`
	Override *HypervisorConfigSpecApplyConfiguration `json:"override,omitempty"`
}

// HypervisorConfigOverrideSpecApplyConfiguration constructs a declarative configuration of the HypervisorConfigOverrideSpec type for use with
// apply.
func HypervisorConfigOverrideSpec() *HypervisorConfigOverrideSpecApplyConfiguration {
	return &HypervisorConfigOverrideSpecApplyConfiguration{}
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *HypervisorConfigOverrideSpecApplyConfiguration) WithReason(value string) *HypervisorConfigOverrideSpecApplyConfiguration {
	b.Reason = &value
	return b
}

// WithOverride sets the Override field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Override field is set to the value of the last call.
func (b *HypervisorConfigOverrideSpecApplyConfiguration) WithOverride(value *HypervisorConfigSpecApplyConfiguration) *HypervisorConfigOverrideSpecApplyConfiguration {
	b.Override = value
	return b
}
