// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HypervisorConfigOverrideStatusApplyConfiguration represents a declarative configuration of the HypervisorConfigOverrideStatus type for use
// with apply.
type HypervisorConfigOverrideStatusApplyConfiguration struct {
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	SpecHash   *string                              `json:"specHash,omitempty"`
}

// HypervisorConfigOverrideStatusApplyConfiguration constructs a declarative configuration of the HypervisorConfigOverrideStatus type for use with
// apply.
func HypervisorConfigOverrideStatus() *HypervisorConfigOverrideStatusApplyConfiguration {
	return &HypervisorConfigOverrideStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HypervisorConfigOverrideStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *HypervisorConfigOverrideStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithSpecHash sets the SpecHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpecHash field is set to the value of the last call.
func (b *HypervisorConfigOverrideStatusApplyConfiguration) WithSpecHash(value string) *HypervisorConfigOverrideStatusApplyConfiguration {
	b.SpecHash = &value
	return b
}
