// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	internal "github.com/cobaltcore-dev/openstack-hypervisor-operator/applyconfigurations/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HypervisorConfigSetApplyConfiguration represents a declarative configuration of the HypervisorConfigSet type for use
// with apply.
//
// HypervisorConfigSet is the Schema for a set of hypervisor configs
type HypervisorConfigSetApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *HypervisorConfigSetSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *HypervisorConfigSetStatusApplyConfiguration `json:"status,omitempty"`
}

// HypervisorConfigSet constructs a declarative configuration of the HypervisorConfigSet type for use with
// apply.
func HypervisorConfigSet(name string) *HypervisorConfigSetApplyConfiguration {
	b := &HypervisorConfigSetApplyConfiguration{}
	b.WithName(name)
	b.WithKind("HypervisorConfigSet")
	b.WithAPIVersion("kvm.cloud.sap/v1")
	return b
}

// ExtractHypervisorConfigSetFrom extracts the applied configuration owned by fieldManager from
// hypervisorConfigSet for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// hypervisorConfigSet must be a unmodified HypervisorConfigSet API object that was retrieved from the Kubernetes API.
// ExtractHypervisorConfigSetFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractHypervisorConfigSetFrom(hypervisorConfigSet *apiv1.HypervisorConfigSet, fieldManager string, subresource string) (*HypervisorConfigSetApplyConfiguration, error) {
	b := &HypervisorConfigSetApplyConfiguration{}
	err := managedfields.ExtractInto(hypervisorConfigSet, internal.Parser().Type("com.github.cobaltcore-dev.openstack-hypervisor-operator.api.v1.HypervisorConfigSet"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(hypervisorConfigSet.Name)

	b.WithKind("HypervisorConfigSet")
	b.WithAPIVersion("kvm.cloud.sap/v1")
	return b, nil
}

// ExtractHypervisorConfigSet extracts the applied configuration owned by fieldManager from
// hypervisorConfigSet. If no managedFields are found in hypervisorConfigSet for fieldManager, a
// HypervisorConfigSetApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// hypervisorConfigSet must be a unmodified HypervisorConfigSet API object that was retrieved from the Kubernetes API.
// ExtractHypervisorConfigSet provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractHypervisorConfigSet(hypervisorConfigSet *apiv1.HypervisorConfigSet, fieldManager string) (*HypervisorConfigSetApplyConfiguration, error) {
	return ExtractHypervisorConfigSetFrom(hypervisorConfigSet, fieldManager, "")
}

// ExtractHypervisorConfigSetStatus extracts the applied configuration owned by fieldManager from
// hypervisorConfigSet for the status subresource.
func ExtractHypervisorConfigSetStatus(hypervisorConfigSet *apiv1.HypervisorConfigSet, fieldManager string) (*HypervisorConfigSetApplyConfiguration, error) {
	return ExtractHypervisorConfigSetFrom(hypervisorConfigSet, fieldManager, "status")
}

func (b HypervisorConfigSetApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithKind(value string) *HypervisorConfigSetApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithAPIVersion(value string) *HypervisorConfigSetApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithName(value string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithGenerateName(value string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithNamespace(value string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithUID(value types.UID) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithResourceVersion(value string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithGeneration(value int64) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *HypervisorConfigSetApplyConfiguration) WithLabels(entries map[string]string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *HypervisorConfigSetApplyConfiguration) WithAnnotations(entries map[string]string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *HypervisorConfigSetApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *HypervisorConfigSetApplyConfiguration) WithFinalizers(values ...string) *HypervisorConfigSetApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *HypervisorConfigSetApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithSpec(value *HypervisorConfigSetSpecApplyConfiguration) *HypervisorConfigSetApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *HypervisorConfigSetApplyConfiguration) WithStatus(value *HypervisorConfigSetStatusApplyConfiguration) *HypervisorConfigSetApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *HypervisorConfigSetApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *HypervisorConfigSetApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *HypervisorConfigSetApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *HypervisorConfigSetApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
