// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HypervisorStatusApplyConfiguration represents a declarative configuration of the HypervisorStatus type for use
// with apply.
//
// HypervisorStatus defines the observed state of Hypervisor
type HypervisorStatusApplyConfiguration struct {
	// Represents the LibVirt version.
	LibVirtVersion *string `json:"libVirtVersion,omitempty"`
	// Represents the Hypervisor version
	HypervisorVersion *string `json:"hypervisorVersion,omitempty"`
	// Represents the Operating System status.
	OperatingSystem *OperatingSystemStatusApplyConfiguration `json:"operatingSystem,omitempty"`
	// Represents the Hypervisor update status.
	Update *HyperVisorUpdateStatusApplyConfiguration `json:"updateStatus,omitempty"`
	// Represents the Hypervisor hosted Virtual Machines
	Instances []InstanceApplyConfiguration `json:"instances,omitempty"`
	// Auto-discovered capabilities as reported by libvirt.
	Capabilities *CapabilitiesApplyConfiguration `json:"capabilities,omitempty"`
	// Auto-discovered domain capabilities relevant to check if a VM
	// can be scheduled on the hypervisor.
	DomainCapabilities *DomainCapabilitiesApplyConfiguration `json:"domainCapabilities,omitempty"`
	// Auto-discovered resource allocation of all hosted VMs.
	Allocation map[apiv1.ResourceName]resource.Quantity `json:"allocation,omitempty"`
	// Auto-discovered capacity of the hypervisor.
	//
	// Note that this capacity does not include the applied overcommit ratios,
	// and represents the actual capacity of the hypervisor. Use the
	// effective capacity field to get the capacity considering the applied
	// overcommit ratios.
	Capacity map[apiv1.ResourceName]resource.Quantity `json:"capacity,omitempty"`
	// Auto-discovered capacity of the hypervisor, considering the
	// applied overcommit ratios.
	//
	// In case no overcommit ratio is specified for a resource type, the default
	// overcommit ratio of 1 should be applied, meaning the effective capacity
	// is the same as the actual capacity.
	//
	// If the overcommit ratio results in a fractional effective capacity, the
	// effective capacity is expected to be rounded down.
	EffectiveCapacity map[apiv1.ResourceName]resource.Quantity `json:"effectiveCapacity,omitempty"`
	// Auto-discovered cells on this hypervisor.
	Cells []CellApplyConfiguration `json:"cells,omitempty"`
	// Represents the number of instances running on this hypervisor.
	NumInstances *int `json:"numInstances,omitempty"`
	// HypervisorID is the unique identifier of the hypervisor in OpenStack.
	HypervisorID *string `json:"hypervisorId,omitempty"`
	// ServiceID is the unique identifier of the compute service in OpenStack.
	ServiceID *string `json:"serviceId,omitempty"`
	// Traits are the applied traits of the hypervisor.
	Traits []string `json:"traits,omitempty"`
	// Aggregates are the applied aggregates of the hypervisor with their names and UUIDs.
	Aggregates []AggregateApplyConfiguration `json:"aggregates,omitempty"`
	// InternalIP is the internal IP address of the hypervisor.
	InternalIP *string `json:"internalIp,omitempty"`
	// Evicted indicates whether the hypervisor is evicted. (no instances left with active maintenance mode)
	Evicted *bool `json:"evicted,omitempty"`
	// Represents the Hypervisor node conditions.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	SpecHash   *string                              `json:"specHash,omitempty"`
}

// HypervisorStatusApplyConfiguration constructs a declarative configuration of the HypervisorStatus type for use with
// apply.
func HypervisorStatus() *HypervisorStatusApplyConfiguration {
	return &HypervisorStatusApplyConfiguration{}
}

// WithLibVirtVersion sets the LibVirtVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LibVirtVersion field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithLibVirtVersion(value string) *HypervisorStatusApplyConfiguration {
	b.LibVirtVersion = &value
	return b
}

// WithHypervisorVersion sets the HypervisorVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HypervisorVersion field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithHypervisorVersion(value string) *HypervisorStatusApplyConfiguration {
	b.HypervisorVersion = &value
	return b
}

// WithOperatingSystem sets the OperatingSystem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingSystem field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithOperatingSystem(value *OperatingSystemStatusApplyConfiguration) *HypervisorStatusApplyConfiguration {
	b.OperatingSystem = value
	return b
}

// WithUpdate sets the Update field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Update field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithUpdate(value *HyperVisorUpdateStatusApplyConfiguration) *HypervisorStatusApplyConfiguration {
	b.Update = value
	return b
}

// WithInstances adds the given value to the Instances field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Instances field.
func (b *HypervisorStatusApplyConfiguration) WithInstances(values ...*InstanceApplyConfiguration) *HypervisorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInstances")
		}
		b.Instances = append(b.Instances, *values[i])
	}
	return b
}

// WithCapabilities sets the Capabilities field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capabilities field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithCapabilities(value *CapabilitiesApplyConfiguration) *HypervisorStatusApplyConfiguration {
	b.Capabilities = value
	return b
}

// WithDomainCapabilities sets the DomainCapabilities field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainCapabilities field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithDomainCapabilities(value *DomainCapabilitiesApplyConfiguration) *HypervisorStatusApplyConfiguration {
	b.DomainCapabilities = value
	return b
}

// WithAllocation puts the entries into the Allocation field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Allocation field,
// overwriting an existing map entries in Allocation field with the same key.
func (b *HypervisorStatusApplyConfiguration) WithAllocation(entries map[apiv1.ResourceName]resource.Quantity) *HypervisorStatusApplyConfiguration {
	if b.Allocation == nil && len(entries) > 0 {
		b.Allocation = make(map[apiv1.ResourceName]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Allocation[k] = v
	}
	return b
}

// WithCapacity puts the entries into the Capacity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Capacity field,
// overwriting an existing map entries in Capacity field with the same key.
func (b *HypervisorStatusApplyConfiguration) WithCapacity(entries map[apiv1.ResourceName]resource.Quantity) *HypervisorStatusApplyConfiguration {
	if b.Capacity == nil && len(entries) > 0 {
		b.Capacity = make(map[apiv1.ResourceName]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Capacity[k] = v
	}
	return b
}

// WithEffectiveCapacity puts the entries into the EffectiveCapacity field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EffectiveCapacity field,
// overwriting an existing map entries in EffectiveCapacity field with the same key.
func (b *HypervisorStatusApplyConfiguration) WithEffectiveCapacity(entries map[apiv1.ResourceName]resource.Quantity) *HypervisorStatusApplyConfiguration {
	if b.EffectiveCapacity == nil && len(entries) > 0 {
		b.EffectiveCapacity = make(map[apiv1.ResourceName]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.EffectiveCapacity[k] = v
	}
	return b
}

// WithCells adds the given value to the Cells field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Cells field.
func (b *HypervisorStatusApplyConfiguration) WithCells(values ...*CellApplyConfiguration) *HypervisorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCells")
		}
		b.Cells = append(b.Cells, *values[i])
	}
	return b
}

// WithNumInstances sets the NumInstances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumInstances field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithNumInstances(value int) *HypervisorStatusApplyConfiguration {
	b.NumInstances = &value
	return b
}

// WithHypervisorID sets the HypervisorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HypervisorID field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithHypervisorID(value string) *HypervisorStatusApplyConfiguration {
	b.HypervisorID = &value
	return b
}

// WithServiceID sets the ServiceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceID field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithServiceID(value string) *HypervisorStatusApplyConfiguration {
	b.ServiceID = &value
	return b
}

// WithTraits adds the given value to the Traits field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Traits field.
func (b *HypervisorStatusApplyConfiguration) WithTraits(values ...string) *HypervisorStatusApplyConfiguration {
	for i := range values {
		b.Traits = append(b.Traits, values[i])
	}
	return b
}

// WithAggregates adds the given value to the Aggregates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Aggregates field.
func (b *HypervisorStatusApplyConfiguration) WithAggregates(values ...*AggregateApplyConfiguration) *HypervisorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAggregates")
		}
		b.Aggregates = append(b.Aggregates, *values[i])
	}
	return b
}

// WithInternalIP sets the InternalIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InternalIP field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithInternalIP(value string) *HypervisorStatusApplyConfiguration {
	b.InternalIP = &value
	return b
}

// WithEvicted sets the Evicted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Evicted field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithEvicted(value bool) *HypervisorStatusApplyConfiguration {
	b.Evicted = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HypervisorStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *HypervisorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithSpecHash sets the SpecHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SpecHash field is set to the value of the last call.
func (b *HypervisorStatusApplyConfiguration) WithSpecHash(value string) *HypervisorStatusApplyConfiguration {
	b.SpecHash = &value
	return b
}
