// Code generated by controller-gen. DO NOT EDIT.

package v1

// HypervisorConfigSetTemplateApplyConfiguration represents a declarative configuration of the HypervisorConfigSetTemplate type for use
// with apply.
type HypervisorConfigSetTemplateApplyConfiguration struct {
	Spec *HypervisorConfigSpecApplyConfiguration `json:"spec,omitempty"`
}

// HypervisorConfigSetTemplateApplyConfiguration constructs a declarative configuration of the HypervisorConfigSetTemplate type for use with
// apply.
func HypervisorConfigSetTemplate() *HypervisorConfigSetTemplateApplyConfiguration {
	return &HypervisorConfigSetTemplateApplyConfiguration{}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *HypervisorConfigSetTemplateApplyConfiguration) WithSpec(value *HypervisorConfigSpecApplyConfiguration) *HypervisorConfigSetTemplateApplyConfiguration {
	b.Spec = value
	return b
}
