// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/cobaltcore-dev/openstack-hypervisor-operator/api/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ReservationBookingApplyConfiguration represents a declarative configuration of the ReservationBooking type for use
// with apply.
type ReservationBookingApplyConfiguration struct {
	Name      *string                                  `json:"name,omitempty"`
	Resources map[apiv1.ResourceName]resource.Quantity `json:"resources,omitempty"`
}

// ReservationBookingApplyConfiguration constructs a declarative configuration of the ReservationBooking type for use with
// apply.
func ReservationBooking() *ReservationBookingApplyConfiguration {
	return &ReservationBookingApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ReservationBookingApplyConfiguration) WithName(value string) *ReservationBookingApplyConfiguration {
	b.Name = &value
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *ReservationBookingApplyConfiguration) WithResources(entries map[apiv1.ResourceName]resource.Quantity) *ReservationBookingApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[apiv1.ResourceName]resource.Quantity, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}
