// Code generated by controller-gen. DO NOT EDIT.

package v1

// TraitGroupApplyConfiguration represents a declarative configuration of the TraitGroup type for use
// with apply.
type TraitGroupApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// TraitGroupApplyConfiguration constructs a declarative configuration of the TraitGroup type for use with
// apply.
func TraitGroup() *TraitGroupApplyConfiguration {
	return &TraitGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TraitGroupApplyConfiguration) WithName(value string) *TraitGroupApplyConfiguration {
	b.Name = &value
	return b
}
