# SPDX-FileCopyrightText: Copyright 2024 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^charts/.*
      - id: end-of-file-fixer
        exclude: ^charts/.*
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
        exclude: .*/(.+_mock\.go|.+deepcopy\.go)$
      - id: go-mod-tidy
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
  - repo: local
    hooks:
      - id: go-unit
        name: go unit tests
        entry: sh -c "gmake check || make check"
        language: system
        pass_filenames: false
      - id: helmify
        name: helmify
        entry: sh -c "gmake helmify || make helmify"
        language: system
        pass_filenames: false
      - id: go-build
        name: go build
        entry: sh -c "gmake build-all || make build-all"
        language: system
        pass_filenames: false
