# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
# Standard Kubernetes label selector wording in generated CRD YAML
ANDed = "ANDed"


[files]
extend-exclude = [
  "go.mod",
]
