# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "openstack-hypervisor-operator"
SPDX-PackageDownloadLocation = "https://github.com/cobaltcore-dev/openstack-hypervisor-operator"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "PROJECT",
  "config/**",
  "charts/**",
  "build/**",
  "applyconfigurations/**",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and cobaltcore-dev contributors"
SPDX-License-Identifier = "Apache-2.0"
