//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: Copyright 2024 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilitiesStatus) DeepCopyInto(out *CapabilitiesStatus) {
	*out = *in
	out.HostMemory = in.HostMemory.DeepCopy()
	out.HostCpus = in.HostCpus.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilitiesStatus.
func (in *CapabilitiesStatus) DeepCopy() *CapabilitiesStatus {
	if in == nil {
		return nil
	}
	out := new(CapabilitiesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Eviction) DeepCopyInto(out *Eviction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Eviction.
func (in *Eviction) DeepCopy() *Eviction {
	if in == nil {
		return nil
	}
	out := new(Eviction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Eviction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionList) DeepCopyInto(out *EvictionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Eviction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionList.
func (in *EvictionList) DeepCopy() *EvictionList {
	if in == nil {
		return nil
	}
	out := new(EvictionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvictionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionSpec) DeepCopyInto(out *EvictionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionSpec.
func (in *EvictionSpec) DeepCopy() *EvictionSpec {
	if in == nil {
		return nil
	}
	out := new(EvictionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictionStatus) DeepCopyInto(out *EvictionStatus) {
	*out = *in
	if in.OutstandingInstances != nil {
		in, out := &in.OutstandingInstances, &out.OutstandingInstances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictionStatus.
func (in *EvictionStatus) DeepCopy() *EvictionStatus {
	if in == nil {
		return nil
	}
	out := new(EvictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperVisorUpdateStatus) DeepCopyInto(out *HyperVisorUpdateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperVisorUpdateStatus.
func (in *HyperVisorUpdateStatus) DeepCopy() *HyperVisorUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(HyperVisorUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hypervisor) DeepCopyInto(out *Hypervisor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hypervisor.
func (in *Hypervisor) DeepCopy() *Hypervisor {
	if in == nil {
		return nil
	}
	out := new(Hypervisor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Hypervisor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigOverride) DeepCopyInto(out *HypervisorConfigOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigOverride.
func (in *HypervisorConfigOverride) DeepCopy() *HypervisorConfigOverride {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorConfigOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigOverrideList) DeepCopyInto(out *HypervisorConfigOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HypervisorConfigOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigOverrideList.
func (in *HypervisorConfigOverrideList) DeepCopy() *HypervisorConfigOverrideList {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorConfigOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigOverrideSpec) DeepCopyInto(out *HypervisorConfigOverrideSpec) {
	*out = *in
	in.Override.DeepCopyInto(&out.Override)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigOverrideSpec.
func (in *HypervisorConfigOverrideSpec) DeepCopy() *HypervisorConfigOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigOverrideStatus) DeepCopyInto(out *HypervisorConfigOverrideStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigOverrideStatus.
func (in *HypervisorConfigOverrideStatus) DeepCopy() *HypervisorConfigOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigOverrideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSet) DeepCopyInto(out *HypervisorConfigSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSet.
func (in *HypervisorConfigSet) DeepCopy() *HypervisorConfigSet {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorConfigSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSetList) DeepCopyInto(out *HypervisorConfigSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HypervisorConfigSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSetList.
func (in *HypervisorConfigSetList) DeepCopy() *HypervisorConfigSetList {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorConfigSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSetSpec) DeepCopyInto(out *HypervisorConfigSetSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSetSpec.
func (in *HypervisorConfigSetSpec) DeepCopy() *HypervisorConfigSetSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSetStatus) DeepCopyInto(out *HypervisorConfigSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSetStatus.
func (in *HypervisorConfigSetStatus) DeepCopy() *HypervisorConfigSetStatus {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSetTemplate) DeepCopyInto(out *HypervisorConfigSetTemplate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSetTemplate.
func (in *HypervisorConfigSetTemplate) DeepCopy() *HypervisorConfigSetTemplate {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSetTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorConfigSpec) DeepCopyInto(out *HypervisorConfigSpec) {
	*out = *in
	if in.OperatingSystemVersion != nil {
		in, out := &in.OperatingSystemVersion, &out.OperatingSystemVersion
		*out = new(string)
		**out = **in
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(bool)
		**out = **in
	}
	if in.EvacuateOnReboot != nil {
		in, out := &in.EvacuateOnReboot, &out.EvacuateOnReboot
		*out = new(bool)
		**out = **in
	}
	if in.LifecycleEnabled != nil {
		in, out := &in.LifecycleEnabled, &out.LifecycleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SkipTests != nil {
		in, out := &in.SkipTests, &out.SkipTests
		*out = new(bool)
		**out = **in
	}
	if in.CustomTraits != nil {
		in, out := &in.CustomTraits, &out.CustomTraits
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Aggregates != nil {
		in, out := &in.Aggregates, &out.Aggregates
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.HighAvailability != nil {
		in, out := &in.HighAvailability, &out.HighAvailability
		*out = new(bool)
		**out = **in
	}
	if in.CreateCertManagerCertificate != nil {
		in, out := &in.CreateCertManagerCertificate, &out.CreateCertManagerCertificate
		*out = new(bool)
		**out = **in
	}
	if in.InstallCertificate != nil {
		in, out := &in.InstallCertificate, &out.InstallCertificate
		*out = new(bool)
		**out = **in
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorConfigSpec.
func (in *HypervisorConfigSpec) DeepCopy() *HypervisorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorList) DeepCopyInto(out *HypervisorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Hypervisor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorList.
func (in *HypervisorList) DeepCopy() *HypervisorList {
	if in == nil {
		return nil
	}
	out := new(HypervisorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HypervisorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorSpec) DeepCopyInto(out *HypervisorSpec) {
	*out = *in
	if in.CustomTraits != nil {
		in, out := &in.CustomTraits, &out.CustomTraits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Aggregates != nil {
		in, out := &in.Aggregates, &out.Aggregates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorSpec.
func (in *HypervisorSpec) DeepCopy() *HypervisorSpec {
	if in == nil {
		return nil
	}
	out := new(HypervisorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HypervisorStatus) DeepCopyInto(out *HypervisorStatus) {
	*out = *in
	in.OperatingSystem.DeepCopyInto(&out.OperatingSystem)
	out.Update = in.Update
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]Instance, len(*in))
		copy(*out, *in)
	}
	in.Capabilities.DeepCopyInto(&out.Capabilities)
	if in.Traits != nil {
		in, out := &in.Traits, &out.Traits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Aggregates != nil {
		in, out := &in.Aggregates, &out.Aggregates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HypervisorStatus.
func (in *HypervisorStatus) DeepCopy() *HypervisorStatus {
	if in == nil {
		return nil
	}
	out := new(HypervisorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingSystemStatus) DeepCopyInto(out *OperatingSystemStatus) {
	*out = *in
	in.FirmwareDate.DeepCopyInto(&out.FirmwareDate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingSystemStatus.
func (in *OperatingSystemStatus) DeepCopy() *OperatingSystemStatus {
	if in == nil {
		return nil
	}
	out := new(OperatingSystemStatus)
	in.DeepCopyInto(out)
	return out
}
