apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openstack-hypervisor-operator.fullname" . }}-manager-role
  labels:
  {{- include "openstack-hypervisor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvm.cloud.sap
  resources:
  - evictions
  - hypervisors
  - hypervisors/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvm.cloud.sap
  resources:
  - evictions/finalizers
  verbs:
  - update
- apiGroups:
  - kvm.cloud.sap
  resources:
  - evictions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openstack-hypervisor-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "openstack-hypervisor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "openstack-hypervisor-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "openstack-hypervisor-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
