# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openstack-hypervisor-operator.fullname" . }}
  labels:
  {{- include "openstack-hypervisor-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "openstack-hypervisor-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
{{- end }}
