# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and cobaltcore-dev contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openstack-hypervisor-operator.fullname" . }}-metrics
  labels:
    control-plane: controller-manager
  {{- include "openstack-hypervisor-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: control-plane
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "openstack-hypervisor-operator.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: https
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
