# permissions for end users to edit hypervisors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kvm-node-agent
    app.kubernetes.io/managed-by: kustomize
  name: hypervisor-editor-role
rules:
- apiGroups:
  - kvm.cloud.sap
  resources:
  - hypervisors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvm.cloud.sap
  resources:
  - hypervisors/status
  verbs:
  - get
